name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
  - cron:  '0 6 * * SAT'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install
    - run: npm run build

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install
    - run: npm test
    - run: bash <(curl -s https://codecov.io/bash) -C $GITHUB_SHA -B ${GITHUB_REF#refs/heads/} -Z
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  update:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@master
    - run: |
        if [[ -n $(git diff --name-only package-lock.json) ]]
        then
          git config user.name "CI Bot"
          git config user.email "\<\>"
          git config credential.helper "store --file=.git/credentials"
          echo "https://${{ secrets.CODECOV_TOKEN }}:@github.com" 2> /dev/null > .git/credentials
          git remote set-url origin https://github.com/$GITHUB_REPOSITORY.git
          git add package-lock.json
          git commit -m "update package-lock.json"
          git push origin HEAD:${GITHUB_REF#refs/heads/} &> /dev/null
        fi
